alab/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('services/', include('services.urls', namespace='services')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from contact.views import ContactView, sendMail

app_name = 'contact'

urlpatterns = [
    path('', ContactView.as_view(), name='contact-page'),
    path('sendMail/', sendMail, name='send-mail'),
]

main/urls.py
from django.urls import path

from main.views import AboutView, HomeView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
]

projects/urls.py
from django.urls import path

from projects.views import ProjectDetailView, ProjectListView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project-list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
]

services/urls.py
from django.urls import path

from services.views import ServiceDetailView, ServiceListView

app_name = 'services'

urlpatterns = [
    path('', ServiceListView.as_view(), name='service-list'),
    path('<int:pk>/', ServiceDetailView.as_view(), name='service-detail'),
]

contact/models.py
from django.db import models

# Create your models here.
class Receipient(models.Model):
    email = models.EmailField()

    class Meta:
        verbose_name = 'Receipient'
        verbose_name_plural = 'Email Receipients'

    def __str__(self):
        return self.email

main/models.py
from unicodedata import name
from django.db import models

from projects.models import Project

# Create your models here.

# clients, featured work
class Client(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'

    def __str__(self):
        return self.name or 'client'


class FeaturedWork(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='featured')

    def __str__(self):
        return self.project.name

projects/models.py
from django.db import models

from services.models import Service, Skill

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=50)
    thumbnail = models.ImageField()
    description = models.TextField(blank=True, null=True)
    client = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    service = models.ForeignKey(Service, related_name='projects', on_delete=models.SET_NULL, null=True, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    
    def __str__(self):
        return self.name


class ProjectPhoto(models.Model):
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='images')
    photo = models.ImageField()

    class Meta:
        verbose_name = 'Project Image'
        verbose_name_plural = 'Project Images'
    
    def __str__(self):
        return f'{self.project.name} photo'

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField()
    short_description = models.TextField(max_length=1000)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    

class Package(models.Model):
    set = models.ForeignKey('PackageSet', on_delete=models.CASCADE, related_name='packages')
    name = models.CharField(max_length=50, default='__package__', blank=True)
    price = models.IntegerField()
    best_choice = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class PackageSet(models.Model):
    name = models.CharField(max_length=60)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='sets')

    class Meta:
        verbose_name = 'Package Set'
        verbose_name_plural = 'Package Sets'

    def __str__(self):
        return self.name or f'{self.service.name} set'



class Item(models.Model):
    package = models.ForeignKey(Package, on_delete=models.CASCADE, related_name='items')
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

contact/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.views.generic import TemplateView
from rest_framework.decorators import api_view
from rest_framework.response import Response

from contact.models import Receipient

# Create your views here.
@api_view(['POST'])
def sendMail(request):
   if request.method == 'POST':
      data = request.data
      message = f"Name: {data.get('name')}\nEmail: {data.get('email')}\nPhone: {data.get('phone')}\nMessage: {data.get('message')}"

      try:
         send_mail(
            subject='Email from contact form on amartislab.com',
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[receipient.email for receipient in Receipient.objects.all()]
         )
         print("\n"+message)

         # return Response('success')
         return Response({"code": "success", "message": "We will get back to you in a moment"})

      except Exception as e:
         print(f'Exception: {e}')
         return Response('{"code": "failure", "message": "Sorry lets find out the issue"}')


class ContactView(TemplateView):
    template_name = "contact/contact.html"

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from main.models import Client, FeaturedWork

# Create your views here.
class HomeView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['works'] = FeaturedWork.objects.all()
        context['clients'] = Client.objects.all()
        return context


class AboutView(TemplateView):
    template_name = "main/about.html"

projects/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from projects.models import Project

# Create your views here.
class ProjectListView(ListView):
    model = Project
    template_name = "projects/project-list.djhtml"
    context_object_name = 'projects'


class ProjectDetailView(DetailView):
    model = Project
    template_name = "projects/project-detail.djhtml"
    context_object_name = 'project'

services/views.py
from django.views.generic import ListView, DetailView

from services.models import Service

# Create your views here.

class ServiceListView(ListView):
    model = Service
    template_name = "services/service-list.djhtml"
    context_object_name = 'services'



class ServiceDetailView(DetailView):
    model = Service
    template_name = "services/service-detail.djhtml"
    context_object_name = 'service'

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load static %}
{% load tailwind_filters %}


{% block styles %}
<style>
	
</style>

{% endblock styles %}


{% block content %}
<section class="">
	<div class="container-fluid">
		<div class="grid grid-cols-1 md:grid-cols-2 min-h-screen">
			<div class="pt-32 grid content-center">
				<div class="ml-auto w-fit p-8 max-w-[1300px]">
					<div id="hero" class="hidden"></div>
					<p class="text-2xl py-2 font-light">
						We highly want, love and anticipate to hear from you about our work, company, website or your projects. <br> So get in touch with us on the platforms indicated below 
					</p>
					<p class="text-xl py-2 font-light">
						or write to us here
					</p>
					<ol class="text-xl mt-4 font-light">
						<li class="my-4"><i class="fas fa-phone mr-4" aria-hidden="true"></i>+256 760 971 269</li>
						<li class="my-4"><i class="fas fa-envelope mr-4"></i>info@amartislab.com</li>
						<!-- <li class="my-1"><i class="fas fa-community mr-4"></i>@amartislab</li> -->
					</ol>
					<div class="flex my-4 text-xl">
						<a class="content-center mr-2 hover:text-pink-500" href="instagram.com/amartislab"><i class="fab fa-instagram"></i></a>
						<a class="content-center mx-2 hover:text-blue-700" href="facebook.com/amartislab"><i class="fab fa-facebook"></i></a>
						<a class="content-center mx-2 hover:text-blue-500" href="twitter.com/amartislab"><i class="fab fa-twitter"></i></a>
						<a class="content-center mx-2 hover:text-green-500" href="wa.me"><i class="fab fa-whatsapp"></i></a>
						<a class="content-center mx-2 mr-4 hover:text-primary-500" href="mailto:info.amartislan.com"><i class="fas fa-envelope"></i></a>@amartislab
					</div>
				</div>
			</div>
			<!-- form -->
			<div class="pt-32 dark:bg-dark-300 bg-white grid content-center">
				<div class=" p-12 h-full">
					<form method="post" class=" max-w-[1500px]" x-data="{
						post_message: false,
						mail: {
							name: '',
							email: '',
							phone: '',
							message: '',
						},
						csrf() {
							token = document.getElementById('token').firstElementChild.value;
							return token;
						 },
						async sendMail() {
							this.status = 'sending...'
							await fetch(`{% url 'contact:send-mail' %}`, {
								method: 'POST',
								headers: {
								   Accept: 'application/json',
								   'Content-Type': 'application/json',
								   'X-CSRFToken': this.csrf(),
								},
								body: JSON.stringify(this.mail),
							 }).then((response) => response.json())
									.then((json) => {
										console.log(json)
										if (json.code === 'success') {
											console.log(json.code)
										// clear fields
											this.mail.name = ''
											this.mail.email = ''
											this.mail.phone = ''
											this.mail.message = ''
											this.post_message = true
										}
									});
							
						 }
					}" @submit.prevent="sendMail()">
						<div id="token">{% csrf_token %}</div>
                        <div class="mb-8">
                            <div class="input-group">
                                <input x-model="mail.name" required type="text" name="your_name" class="input dark:bg-dark-100 dark:text-white" />
                                <label class="user-label dark:text-white" for="your_name">Name</label>
                            </div>
                        </div>
                        <div class="grid lg:grid-cols-2 gap-4">
                            <div class="input-group">
                                <input x-model="mail.email" required type="email" name="your_email" class="input dark:bg-dark-100 dark:text-white" />
                                <label class="user-label dark:text-white" for="your_email">Email</label>
                            </div>
                            <div class="input-group">
                                <input x-model="mail.phone" required type="tel" name="your_phone" class="input dark:bg-dark-100 dark:text-white" />
                                <label class="user-label dark:text-white" for="your_phone">Phone</label>
                            </div>
                        </div>
                        <div class="my-8">
                            <div class="input-group">
                                <textarea x-model="mail.message" required name="your_message" class="input dark:bg-dark-100 dark:text-white" rows="10"></textarea>
                                <label class="user-label dark:text-white" for="your_message">Message</label>
                            </div>
                        </div>
                        <div class="mt-8 flex">
                            <button type="submit" class=" bg-primary-900 py-4 px-8 hover:bg-primary-500 font-semibold text-xl"><i class="fab fa-telegram mr-3"></i>Send</button>
							<span class="my-auto uppercase ml-8 text-white font-bold" x-show="post_message" x-cloak>
								<i class="fa fa-check text-green-400 mr-4" aria-hidden="true"></i> Success
							</span>
                        </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}


{% block scripts %}
{% endblock scripts %}

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- hero section -->
<section class="py-60">
    <div id="hero"></div>
	<div class="container grid justify-center">
		<figure class="mx-auto">
			<img src="{% static '/img/text-logo.png' %}" alt="Amartislab" class="" />
		</figure>
		<p class="lead text-center mx-auto mt-8 max-w-xl">
			Logos, Adverts, Posters, Websites, Banners, video editing Product visualization, animation,
			visual effects
		</p>
	</div>
</section>
<!--end hero-->

<!-- who we are -->
<section class="py-5 my-40">
    <h2 class="header-1">Who we are</h2>
    <div class="container mt-12">
        <div class="grid md:grid-cols-2 md:grid-rows-2 gap-8">
            <div class="max-w-xl md:row-span-2 md:ml-auto">
                <h3 class="header-2">About us</h3>
                <p class=" mt-8 lead">
                    Started by Allan Martin Ssebagala, a creative director and brand strategist with a reputation for epic work, Amartislab is a next generation agency delivering brand design and brand marketing solutions. Our agile agency model is built on an extensive network of highly talented strategic and creative professionals who work collaboratively with clients worldwide to meet their business objectives.
                </p>
            </div>
            <div class="max-w-xl">
                <h3 class="header-2">Our vision</h3>
                <p class=" mt-8 lead">
                    To be a place of choice for exellence and inspiration.
                </p>
            </div>
            <div class="max-w-xl">
                <h3 class="header-2">Our Mission</h3>
                <p class=" mt-8 lead">
                    Creating inspirational and innovative designs to connect clients and customers.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- what we do -->
<section class="py-5 my-40">
    <h2 class="header-1">What do we do</h2>
    <div class="mt-12 pr-3">
        <div class="grid grid-cols-2">
            <div class=" pr-3">
                <video src="{% static 'video/aboutus.m4v' %}"></video>
            </div>
            <div>
                <p class="lead max-w-xl">
                    Started by Alfredo Muccino, a creative director and brand strategist with a reputation for award-winning work, Solid is a next generation agency delivering brand strategy, brand design and brand marketing solutions. Our agile agency model is built on an extensive network of highly talented strategic and creative professionals who work collaboratively with clients worldwide to meet their business objectives.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- our approach -->
<section class="py-5 my-40">
    <h2 class="header-1">How we approach projects</h2>
    <div class="mt-12">
        <div class="grid sm:grid-cols-1 md:grid-cols-2 my-40">
            <div>
                <div class=" max-w-lg ml-auto mr-10">
                    <h3 class="header-2">Fast Execution</h3>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem cupiditate esse dolore dicta perferendis corporis officia totam non odit. Eveniet reiciendis porro dignissimos iste minus doloribus repellendus quisquam vero non!
                </p>
                </div>
            </div>
            <div>
                <img src="/img/excecution/people.png" alt="Collaborative excecution" class="w-full h-full object-contain">
            </div>
        </div>
        <div class="grid sm:grid-cols-1 md:grid-cols-2 my-40">
            <div>
                <img src="/img/excecution/people.png" alt="Collaborative excecution" class="w-full h-full object-contain">
            </div>
            <div>
                <div class=" max-w-lg mr-auto ml-10">
                    <h3 class="header-2">Satisfaction guarantee</h3>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem cupiditate esse dolore dicta perferendis corporis officia totam non odit. Eveniet reiciendis porro dignissimos iste minus doloribus repellendus quisquam vero non!
                </p>
                </div>
            </div>
        </div>
        <div class="grid sm:grid-cols-1 md:grid-cols-2 my-40">
            <div>
                <div class=" max-w-lg ml-auto mr-10">
                    <h3 class="header-2">Creative design</h3>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem cupiditate esse dolore dicta perferendis corporis officia totam non odit. Eveniet reiciendis porro dignissimos iste minus doloribus repellendus quisquam vero non!
                </p>
                </div>
            </div>
            <div>
                <img src="/img/excecution/people.png" alt="Collaborative excecution" class="w-full h-full object-contain">
            </div>
        </div>
        <div class="grid sm:grid-cols-1 md:grid-cols-2 my-40">
            <div>
                <img src="/img/excecution/people.png" alt="Collaborative excecution" class="w-full h-full object-contain">
            </div>
            <div>
                <div class=" max-w-lg mr-auto ml-10">
                    <h3 class="header-2">Collaborative design</h3>
                <p class="lead">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem cupiditate esse dolore dicta perferendis corporis officia totam non odit. Eveniet reiciendis porro dignissimos iste minus doloribus repellendus quisquam vero non!
                </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <Poly/>
    </div>
</section>
{% endblock content %}
    

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!-- hero section -->
<section class="bg-white dark:bg-black">
    <div id="hero"></div>
    <div class="container grid justify-center py-72">
        <h1 class="uppercase text-7xl font-bold text-center">Your Brand, Your Story</h1>
        <div class="grid sm:grid-cols-3 gap-4 mx-auto text-center mt-10">
            <PolyButton text="Services" link="/services" cls="primary"/>
            <PolyButton text="Work" link="/work"/>
            <PolyButton text="Contact" link="/contact"/>
        </div>
    </div>
</section> <!--end hero-->

<!-- about -->
<section class="py-5 my-40">
        <h2 class="uppercase text-6xl font-bold text-center">Who are we?</h2>

    <div class="grid sm:grid-cols-2 md:grid-cols-2 mt-12 container">
        <!-- achievements -->
        <div class="flex justify-end">
            <div class="grid grid-cols-2 gap-4 w-full">
                <!-- cards here -->
                <Counter number="20" text="Satisfied Customers"/>
                <Counter number="50" text="Designs Made"/>
                <Counter number="20" text="Videos Produced"/>
                <Counter number="20" text="Satisfied Customers"/>
            </div>
        </div>
        <!-- about us -->
        <div>
            <p class="sm:ml-6 mt-8 max-w-xl lead text-center sm:text-left">
                Amarti's lab is a next generation agency delivering brand design, web development, animation
				and visual effects. Our agile agency model is built on an extensive network of highly
				talented strategic and creative professionals who work collaboratively with clients
				worldwide to meet their business objectives.
            </p>
        </div>
    </div>
</section>

<!-- What we do -->
<section class="py-5 my-40">
    <h2 class="header-1">What do we do?</h2>
    <div class="container mt-12">
        <!-- cards go here -->
        <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-12 relative">
            <div class="card bg-green-900 before:bg-green-100 ">
                <h3 class=" font-semibold text-2xl text-green-100">Web Development</h3>
                <p class=" font-light mt-4 text-green-100">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla est fugit ipsa quo doloremque saepe id.
                </p>
            </div>
        </div>
    </div>
</section>
<!-- 
    hover:before:-z-10  before:-z-10  before:top-0 before:left-0 before:blur-lg before:opacity-80 before:translate-x-0 before:translate-y-0 before:transition-all hover:before:opacity-20 hover:before:-translate-x-8 hover:before:translate-y-10
 -->

<!-- featured projects -->
<section class="py-5 my-40">
    <h2 class="header-1">Our featured work</h2>
    <div class="container mt-12">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            
            {% for work in works %}
                <div class=" aspect-square">
                    <img src="{{ work.project.thumbnail.url }}" alt="{{ work.project.name }}" class=" object-cover h-full w-full">
                </div>
            {% endfor %}
                
        </div>
    </div>
</section>

<!-- clients -->
<section class="py-5 my-40">
    <h2 class="header-1">Our notable clients</h2>
    <div class="container mt-12">
        <div class="grid grid-cols-2 xl:grid-cols-5 gap-4 justify-center">
            
            {% for client in clients %}
                <figure class=" h-28 aspect-video grid place-content-center p-3">
                    <img src="{{ client.image.url }}" alt="{{ client.name }}" class=" fluid">
                </figure>
            {% endfor %}
                
        </div>
    </div>
</section>

<!-- call to action -->
<section>
    <div class="container">
        <div class=" bg-primary-900 p-16 rounded-tr-[5rem] rounded-bl-[5rem]">
            <div class="grid sm:grid-cols-2">
                <figure></figure>
                <div>
                    <h2>Ready to get in touch with us</h2>
                    <button class="text-primary-900 py-4 px-8 bg-white rounded-tr-xl rounded-bl-xl font-bold text-xl">
                        Send us a message
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" /> 
		<link rel="icon" href="{% static 'img/favicon.png' %}" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!-- %sveltekit.head% -->
		<!-- <script src="https://kit.fontawesome.com/09c907f758.js" crossorigin="anonymous"></script> -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome-free-6.1.1-web\css\all.min.css' %}">
        <script defer src="{% static 'lib/alpine.js' %}"></script>
        
        {% block styles %}
        {% endblock styles %}
		<style>
			[x-cloak]{
				display: none;
			}
			/* From uiverse.io by @satyamchaudharydev */
			/* The switch - the box around the slider */
			.switch {
				/* --moon-mask: ; */
				font-size: 17px;
				position: relative;
				display: inline-block;
				width: 3.5em;
				height: 2em;
				transform: scale(0.7);
			}
		
			/* Hide default HTML checkbox */
			.switch input {
				opacity: 0;
				width: 0;
				height: 0;
			}
		
			/* The slider */
			.slider {
				position: absolute;
				cursor: pointer;
				top: 0;
				left: 0;
				right: 0;
				bottom: 0;
				background-color: #f4f4f5;
				transition: 0.4s;
				border-radius: 30px;
			}
		
			.slider:before {
				position: absolute;
				content: '';
				height: 1.4em;
				width: 1.4em;
				border-radius: 20px;
				left: 0.3em;
				bottom: 0.3em;
				background: linear-gradient(40deg, #ff0080, #ff8c00 70%);
				transition: 0.4s;
			}
		
			input:checked + .slider {
				background-color: #303136;
			}
		
			input:checked + .slider:before {
				transform: translateX(1.5em);
				background: #303136;
				box-shadow: inset -3px -2px 5px -2px #8983f7, inset -10px -5px 0 0 #a3dafb;
			}
		</style>
	</head>
	<body class="dark:text-white dark:bg-dark-100 bg-light-100 xl:text-lg font-body">
		{% include 'components/header.html' %}
		<div class="">
            {% block content %}
            {% endblock content %}
        </div>
		{% include 'components/footer.html' %}

		<!-- <script src="%sveltekit.assets%/js/theme.js"></script> -->
        <script src="{% static 'js/main.js' %}"></script>
        
        {% block scripts %}
        {% endblock scripts %}
	</body>
</html>

templates/components/footer.html
<footer>
    <!-- copyright -->
    <div class="text-center p-5">
        Amartislab &copy; 2022
    </div>
</footer>

templates/components/header.html
<nav class="fixed w-full bottom-0 top-auto z-10 sm:top-0 sm:bottom-auto backdrop-blur-sm" id="navbar-sticky">
    <div class="py-2 c-blur">
        <div class="container">
            <div class="flex justify-between content-center pr-3">
                <div class="flex flex-1 content-center">
                    <div class=" grid content-center">
                        <span class="switch">
                            <input type="checkbox" id="themeToggle" />
                            <span class="slider"></span>
                        </span>
                    </div>
                    <a class="content-center mx-2 hidden sm:grid" href="instagram.com/amartislab"><i class="fab fa-instagram"></i></a>
                    <a class="content-center mx-2 hidden sm:grid" href="facebook.com/amartislab"><i class="fab fa-facebook"></i></a>
                    <a class="content-center mx-2 hidden sm:grid" href="twitter.com/amartislab"><i class="fab fa-twitter"></i></a>
                    <a class="content-center mx-2 hidden sm:grid" href="wa.me"><i class="fab fa-whatsapp"></i></a>
                </div>
                <div class="">
                    <a class="navbar-brand" href="/">
                        <svg viewBox="0 0 272 270" class=" w-14 xl:w-16">
                            <path class="st0 dark:stroke-white"
                                d="M154,178h105.77c4.68-13.47,7.23-27.94,7.23-43c0-66.24-49.17-120.99-113-129.76V178z" />
                            <path class="st0 dark:stroke-white"
                                d="M154,214h-36v-36V70.75L31.89,214.51C55.83,245.81,93.55,266,136,266c42.68,0,80.58-20.41,104.5-52H154z" />
                            <path class="st0 dark:stroke-white"
                                d="M115.01,5.68C52.64,15.73,5,69.8,5,135c0,14.89,2.49,29.2,7.07,42.54L115.01,5.68z" />
                        </svg>
                    </a>
                </div>
                <div class="flex flex-1 justify-end gap-2">
                    <a href="{% url 'main:home' %}" class="uppercase hidden sm:grid content-center">Home</a>
                    <a href="{% url 'main:about' %}" class="uppercase hidden sm:grid content-center">About</a>
                    <a href="{% url 'services:service-list' %}" class="uppercase hidden sm:grid content-center">Services</a>
                    <a href="{% url 'projects:project-list' %}" class="uppercase hidden sm:grid content-center">Work</a>
                    <a href="{% url 'contact:contact-page' %}" class="uppercase hidden sm:grid content-center">Contact</a>
                    <span id="menuToggle" class="uppercase sm:hidden grid content-center"><i
                            class="fas fa-bars"></i></span>
                </div>
            </div>
        </div>
    </div>
</nav>